user/urls.py
from django.urls import path
from .views import *  

app_name = 'user'  #user 앱 이름 명시-> user: 로 이용

urlpatterns = [
    # USER
    path('signup/', signup, name='signup'), # 회원가입
    path('signin/', signin, name='signin'), # 로그인 
    path('signout/', signout, name='signout'), # 로그아웃
    
    # PROFILE 
    path('new_profile/', new_profile, name='new_profile'), # 새 프로필 만드는 창  
    path('create_profile/', create_profile, name='create_profile'),  # 프로필 생성 작업 

    
    ]

user/models.py
from django.db import models
# 장고 기본 제공
# from django.contrib.auth.models import User

# 커스텀
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

# Create your models here.


# AbstractBaseUser로 CustomUser 만들면 CustomUserManager로 관리
# 커스텀 위해 UserManager을 대신 BaseUserManager 사용

# 커스텀 유저 매니저 (관리자)
class CustomUserManager(BaseUserManager):
  # 유저 생성 기본 함수 
  def create_user(self, username,email, password, **kwargs):  # username, password, 기타(딕셔너리형)을 파라미터로 받는다. 
    if not username:
      raise ValueError("must have user name!!")
    if not email:
      raise ValueError("must have user email!!")
    
    user = self.model(username=username, email=self.normalize_email(email), **kwargs) 
    user.set_password(username=username, **kwargs) 
    user.save() #db에 저장
  
  # 일반 유저 생성 
  def create_normaluser(self, username,email, password, **kwargs):
    self.create_user(username, email , password,**kwargs) 
  
  # 슈퍼 유저 생성
  def create_superuser(self, username,email, password, **kwargs):
    kwargs.setdefault("is_superuser", True) 
    self.create_user(username, email, password, **kwargs)
  
  
  
# AbstractBaseUser: Django가 기본 제공하는 User모델을 대체하기 위해 사용되는 추상 클래스
# PermissionsMixin : User 모델에 대한 권한 부여하기 위한 클래스 

# 커스텀 유저 모델 
class CustomUser(AbstractBaseUser, PermissionsMixin):
  objects = CustomUserManager() #커스텀유저가, 커스텀유저매니저를 사용하겠다. 
  
  USERNAME_FIELD = 'username'   #인증 시, username 필드로 유저를 식별하겠다. 
  
  username = models.CharField(unique = True, max_length=20) 
  created_at = models.DateTimeField(auto_now_add=True) 
  updated_at = models.DateTimeField(auto_now=True)
  
  
  @property #is_staff를 속성처럼 사용
  def is_staff(self):
    return self.is_superuser  #
  
  
  
# 프로필 모델
class Profile(models.Model):
  #프로필:유저 = 일대일 관계
  user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name="profile", null=True)
  nickname = models.CharField(max_length=20, null=True) 
  image = models.ImageField(upload_to='profile/', null=True)
  
  class Meta:
     db_table='profile'
  
  def __str__(self):
    return self.nickname  
  

user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser  

# UserCreationForm
# AuthenticationForm


# 회원 가입 폼 -> 회원가입 시 유효성 검사
class CustomUserSignupForm(UserCreationForm):
  class Meta:
    model = CustomUser
    fields = ['username']
    

# 로그인 (인증) 폼 -> 로그인 시 유효성 검사
class CustomUserSigninForm(AuthenticationForm):
  class Meta(UserCreationForm.Meta):
    models = CustomUser
    fields = ['username'] 

user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout #장고 제공 로그인, 로그아웃 사용
# 폼 사용 
from .forms import CustomUserSignupForm, CustomUserSigninForm

# 모델 사용 
from .models import CustomUser, Profile 


# Create your views here.

# 회원 가입
def signup(request):
  form = CustomUserSignupForm() #폼 생성 
  
  #착한 사용자 
  if request.method == "POST":
    form = CustomUserSignupForm(request.POST)  #사용자의 입력값만 유효한지 판단 

  
    if form.is_valid(): # 유효할 경우 
      user = form.save()  #폼 데이터를 db에 저장 
      login(request, user)  #장고 제공 login() 
      return redirect("home")  #회원가입 후 메인홈으로 이동 
  
  #나쁜 사용자   
  return render(request, "newSignup.html", {"form" : form}) 
  #회원가입 페이지로 이동 , 유효성 검사 하도록 객체도 함께 전달


  
# 로그인
def signin(request):
  form = CustomUserSigninForm() #폼 객체 생성 
  
  #착한 사용자
  if request.method == "POST":
    form = CustomUserSigninForm(request, request.POST) 
    
    if form.is_valid(): #유효하다면
      login(request, form.get_user()) #로그인 -> db에서 일치하는지만 확인! / db save() 필요 없음
      return redirect('home') #로그인 후 메인홈으로 이동
    
  #나쁜 사용자 
  return render(request, "newSignin.html", {"form" : form})
  

# 로그아웃
def signout(request):
  logout(request)
  return redirect("home") #유저 로그아웃 후 메인홈으로 이동

# 프로필 
def new_profile(request):
  # 로그인 하지 않았다면, 프로필을 누르더라도 계속 홈으로 이동 
  if request.user.is_anonymous:
    return redirect("home") 
  
  # 로그인 했다면 -> 해당 유저의 프로필 보여주기
  profile, created = Profile.objects.get_or_create(user=request.user) 
  
  # request.user : 현재 요청 보내는 유저
  # get_or_created(조건) 메서드 : 주어진 조건에 따라 객체를 가져오거나 존재하지 않으면 생성
  # user=request.user : user 필드가 request.user와 일치하는 프로필을 가져오거나 생성할 것을 지정
  # 반환 : 1. 가져온(생성된) 프로필 객체  2.객체가 새로 생성되었는지 여부를 나타내는 bool값 -> 이 값을 created에 지정
  
  # created == False : 이미 해당 유저의 프로필 객체가 존재해서 get했음(새로 생성X)
  # created == True : 해당 유저의 프로필 객체가 존재하지 않아서 새로 생성했음
  
  return render(request, "newProfile.html", {"profile":profile}) #가져온 프로필 객체를 전달, 프로필 페이지로 이동



# 프로필 생성 작업
def create_profile(request):
  profile, created = Profile.objects.get_or_create(user=request.user)
  
  if request.method == 'POST':
        profile.nickname = request.POST.get('nickname')
        profile.image = request.FILES.get('image')
        profile.save()
        return redirect('user:new_profile')

  return render(request, 'newProfile.html', {'profile': profile})

user/templates/login.html
{% extends 'base.html' %} {% block content %}
<div class="wrapper">
  <div style="text-align: center">
    <h1>로그인</h1>
    <form method="POST">
      {% csrf_token %} 아이디:
      <br />
      <input name="username" type="text" />
      <br />
      비밀번호:
      <br />
      <input name="password" type="password" />
      <br /><br />
      <input type="submit" class="btn btn-primary" value="Login" />
    </form>
  </div>
</div>
{% endblock %}

user/templates/newProfile.html
<h1>프로필</h1>
<hr>

<h2>계정 정보</h2>
<p>아이디: {{ user.username }}</p>
<hr>

<h2>프로필 정보</h2>
<form method="post" enctype="multipart/form-data" action="{% url 'user:create_profile' %}">
    {% csrf_token %}
    <label for="nickname">닉네임:</label>
    <input type="text" name="nickname" id="nickname" value="{{ profile.nickname }}"><br><br>
    
    <label for="image">프로필 사진:</label>
    {% if profile.image %}
    <img src="{{ profile.image.url }}" alt="프로필 사진" width="100"><br>
    
    <label>
        <input type="checkbox" name="remove_image"> 사진 삭제
    </label><br><br>
    {% endif %}
    <input type="file" name="image" id="image"><br><br>
    <button type="submit">저장</button>
</form>

<a href="{% url 'home' %}">홈으로 가기</a>

user/templates/newSignin.html
<h1>Signin 페이지입니다 ;> </h1>

<form method="POST" action="{%url 'user:signin'%}">
  {%csrf_token%}  
  {{ form }} 
  <input type="submit" value="로그인하기"/>


</form>


<a href="{% url 'home' %}">홈으로 가기!! </a> 

user/templates/newSignup.html
<h1>Signup 페이지입니다 :> </h1>

<form method="POST" action="{%url 'user:signup'%}">
  {% csrf_token %}  
  {{ form }} 
  <input type="submit" value="회원가입하기"/>


</form>


<a href="{% url 'home' %}">홈으로 가기!! </a> 

user/templates/signup.html
{% extends 'base.html' %} 


{% block title %}  회원가입 페이지 {%endblock title%}

{% block content %}
<div class="wrapper" style="text-align: center">
  <h1>회원가입</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %} 아이디: <br />
    <input name="username" type="text" />
    <br />
    비밀번호: <br />
    <input name="password1" type="password" />
    <br />
    비밀번호 확인: <br />
    <input name="password2" type="password" />
    <br />
    이메일: <br />
    <input name="email" type="email" />
    <br />
    닉네임: <br />
    <input name="nickname" type="text" />
    <br /><br />
    사진 : <input type="file" name="profile_image" />
    <br />
    <input type="submit" class="btn btn-primary" value="Sign Up" />
  </form>
</div>
{% endblock %}